DROP TABLE IF EXISTS inputs;
DROP TABLE IF EXISTS tokens;

CREATE TABLE inputs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    dispatcher VARCHAR(15) NOT NULL DEFAULT '0.0.0.0',
    ipaddress VARCHAR(15) UNIQUE NOT NULL DEFAULT '0.0.0.0',
    ipversion ENUM('IPv4', 'IPv6') NOT NULL DEFAULT 'IPv4',
    note TINYTEXT
);

CREATE TABLE tokens (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    token VARCHAR(20) NOT NULL DEFAULT '123456789abcdefghijk'
);